version: '3.3'

services:
  db:
    image: postgres:13.4
    volumes: 
      - mydb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medicles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  promed:
      volumes:
        - .:/app
      environment:
        - SECRET_KEY=django-insecure-ee%aggxdqkr@d_-hz2&^@g2ru_d4ywvjn-@+53p+&q9)j)+#ln
        - DATABASE_NAME=medicles
        - DATABASE_USER=ramazan
        - DATABASE_PASSWORD= ramazan123
        - DATABASE_HOSTNAME=db
        - DATABASE_PORT=5432
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        - DATABASE_NAME=medicles
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - DATABASE_HOSTNAME=db
        - DATABASE_PORT=5432
        - SECRET_KEY=django-insecure-ee%aggxdqkr@d_-hz2&^@g2ru_d4ywvjn-@+53p+&q9)j)+#ln
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      ports:
          - "8000:8000"
      depends_on: 
          - db
volumes: 
  mydb: