# Generated by Django 3.1.1 on 2021-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_json',
            field=models.JSONField(default='Old Implementation'),
        ),
    ]
