# Generated by Django 3.1.1 on 2021-12-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_action_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
    ]
