# Generated by Django 3.1.1 on 2022-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20211220_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('1', 'Follow'), ('2', 'Unfollow'), ('3', 'Search'), ('4', 'Favourite'), ('5', 'Unfavourite'), ('6', 'Annotate')], max_length=255),
        ),
    ]
