# Generated by Django 3.1.1 on 2021-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmodel',
            name='article_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
