# Generated by Django 3.1.1 on 2022-01-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_annotationmodel_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationmodel',
            name='article_id',
        ),
    ]
