# Generated by Django 3.1.1 on 2021-12-12 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicles', '0006_auto_20210620_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('annotation_value', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ManyToManyField(to='medicles.Article')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
