# Generated by Django 3.1.1 on 2021-11-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0006_auto_20210620_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
