# Generated by Django 3.1.1 on 2021-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0007_auto_20211128_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
