# Generated by Django 3.1.1 on 2021-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0009_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
