# Generated by Django 3.1.1 on 2021-12-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0010_auto_20211213_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
    ]
