# Generated by Django 3.1.1 on 2021-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0011_auto_20211213_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_json',
            field=models.JSONField(default=dict),
        ),
    ]
