# Generated by Django 3.1.1 on 2022-01-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0012_annotation_annotation_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='article_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
