# Generated by Django 3.1.1 on 2022-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0015_auto_20220106_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
